import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Title } from "../components/Typography";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>React Burner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Title>React Burner</Title>
    </div>
  );
}
